"""Create markets and outcomes tables

Revision ID: 0e1036b0f723
Revises: 001
Create Date: 2026-01-05 21:10:51.322209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1036b0f723'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_outcome', sa.String(), nullable=True),
    sa.Column('resolution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_points_per_user', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_category'), 'markets', ['category'], unique=False)
    op.create_index(op.f('ix_markets_created_at'), 'markets', ['created_at'], unique=False)
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_index(op.f('ix_markets_slug'), 'markets', ['slug'], unique=True)
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    op.create_index(op.f('ix_markets_title'), 'markets', ['title'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'name', name='uq_outcome_market_name')
    )
    op.create_index(op.f('ix_outcomes_id'), 'outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_outcomes_market_id'), 'outcomes', ['market_id'], unique=False)
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_outcomes_market_id'), table_name='outcomes')
    op.drop_index(op.f('ix_outcomes_id'), table_name='outcomes')
    op.drop_constraint('uq_outcome_market_name', 'outcomes', type_='unique')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_markets_title'), table_name='markets')
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_index(op.f('ix_markets_slug'), table_name='markets')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_created_at'), table_name='markets')
    op.drop_index(op.f('ix_markets_category'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###

