"""Add rules and image_url to markets

Revision ID: 5bd55d9dd297
Revises: 0e1036b0f723
Create Date: 2026-01-05 21:30:06.109467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd55d9dd297'
down_revision = '0e1036b0f723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('rules', sa.Text(), nullable=True))
    op.add_column('markets', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'image_url')
    op.drop_column('markets', 'rules')
    # ### end Alembic commands ###

